kind: pipeline
name: Ofox_builder

clone:
  depth: 1

steps:
  - name: setup
    image: ghcr.io/sushrut1101/docker:arch
    environment:
      DT_LINK:
        from_secret: DT_LINK
      TG_CHAT_ID:
        from_secret: CHAT_ID
      TG_TOKEN:
        from_secret: TOKEN
      DEVICE:
        from_secret: DEVICE
      OEM:
        from_secret: OEM

    commands:
      - "export DT_LINK=$DT_LINK"
      - "export TG_CHAT_ID=$TG_CHAT_ID"
      - "export TG_TOKEN=$TG_TOKEN"
      - "export TARGET=bootimage"
      - "export OUTPUT=OrangeFox*.zip"
      - "export SYNC_PATH=$HOME/work"
      - "export USE_CCACHE=1"
      - "export CCACHE_SIZE=50G"
      - "export CCACHE_DIR=$HOME/work/.ccache"
      - "export J_VAL=16"
      - "export DEVICE=$DEVICE"
      - "export OEM=$OEM"
      - "cp scripts/* ."
      - "bash check.sh"
      - "bash sync.sh"
      - "bash build.sh"
      - "bash upload.sh"
  #    - curl -sL "https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/checks.sh" | bash
  #    - curl -sL "https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/sync.sh" | bash
  #    - curl -sL "https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/build.sh" | bash
      - "export TIMEOUT=43200"
  #    - curl "https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/upload.sh" | bash
