version: 2.1
jobs:
  compile:
    docker:
      - image: ghcr.io/sushrut1101/docker:arch
    steps:
      - run:
          command: |
            git config --global user.name "tomyprs"
            git config --global user.email "tomy.prs25@gmail.com"
            git config --global color.ui false
            export FOX_BRANCH="fox_12.1"
            export DT_LINK=$DT_LINK
            export DEVICE=$DEVICE
            export OEM=$OEM
            export TARGET="bootimage"
            export OUTPUT="OrangeFox*.zip"
            export SYNC_PATH="$HOME/work" # Full (absolute) path.
            export USE_CCACHE=1
            export CCACHE_SIZE="50G"
            export CCACHE_DIR="$HOME/work/.ccache"
            export J_VAL=16
            export TG_TOKEN=$TOKEN
            export TG_CHAT_ID=$CHAT_ID
            curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/checks.sh | bash
            curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/sync.sh | bash
            curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/build.sh | bash

workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
